name: User Acceptance Testing
on:
  pull_request:
    branches: [master]
jobs:
  build-test-and-deploy:
    name: Build Test and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [12.x]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      DEST_DIR: 'mashrukh-islam/iTunesSearch'
      SOURCE_DIR: './build/'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks 
      - name: Update PR
        uses: tzkhan/pr-update-action@v2
        with:
          repo_token: ${{ env.GITHUB_TOKEN }}
          body_template: http://${{ env.AWS_S3_BUCKET }}}.s3-website.${{ env.AWS_REGSION }}.amazonaws.com/${{ env.DEST_DIR }}/

